#!/bin/sh

set -eu

cd "$(dirname "$0")"
export MIX_ENV=test

mix deps.get --check-locked
npm ci --ignore-scripts
mix compile --warnings-as-errors
mix format --check-formatted
npm run format:check
npm test
